---
layout: page
title: False positives
output:
  #  md_document:
  github_document:
    pandoc_args: --webtex
#    variant: markdown_github
  preserve_yaml: true
bibliography: [../references/referencesMRbook.bib]
csl: [../references/apa-6th-edition.csl]
---

```{r , echo = FALSE, eval = TRUE}
#knitr::opts_knit$set(base.dir = "/home/rafal/L2/L2projects/backtesting",
knitr::opts_knit$set(base.dir = "/home/rafal/UG/UGprojects/rfl-urbaniak.github.io",
base.url = "https://rfl-urbaniak.github.io/")
knitr::opts_chunk$set(fig.path = "images/")
```


However, while DNA evidence seems as scientific as it gets, the risk of a false positive is not negligible [@Shaer2016False].  For instance, Houston Police Department Crime Laboratory, a large public forensic center in Texas, handles around 500 cases a year. In 2016, KHOU 11, a local television station, sent dozens of profiles processed by the lab to independent experts. The results were not optimistic: police technicians quite systematically misinterpreted samples.


One notorious case involving a false positive is that of  Josiah Sutton (then 16) and Gregory Adams (then 19), who were arrested for a rape of a 41-year-old woman. The victim was abducted in a parking lot and assaulted in a driving car (Ford Expedition). A few days after the incident, the victim spotted Sutton and Adams walking down a street, flagged down a patrol car, and accussed them of the assault. Both Sutton and Adams had alibis, neither of them matched the victim's original description of the perpetrators. Sutton and Adams agreed to a DNA test to clear their names.  A Houston lab analyst Christy Kim compared their results with DNA obtained from a  vaginal swab, which  contained a mixture of genetic material from at least three contributors, including the victim herself. The lab report did not report a match for Adams, but concluded that Sutton's DNA was consistent with the mixture DNA. In result, in 1999, Sutton was sentenced to 25 years in prison. Later on, a re-examination by prof. William Thompson, indicated that the three DNA profiles typed by Kim (two from blood, one from saliva) varied, despite reportedly coming from a single source. Moreover, Kim failed to report that the DNA from the semen found on the car seat did not match that of Sutton. In effect, the DNA evidence was reprocessed, no DNA match was found, and in 2003 Sutton was released from prison.^[Christy Kim later on sued her employer for her firing that resulted and won, her mistakes being atttributed to systemic failures  and inadequate supervision.]



This is only one example of quite a few  cases of DNA matching going awry, and the existing anecdotal evidence suggests there are quite a few potential sources of error. See for instance @thompson2012forensic for a more exhaustive treatment and multiple examples.
